/*
Name: EECS 348 Assignment 2
Description: C program that prioritizes emails for a CEO using a list-based MaxHeap priority queue.
Inputs: Text commands (EMAIL, NEXT, READ, COUNT) via standard input.
Output: Prioritized email details and queue counts based on sender category and date.
Collaborators: GenAI (Google Gemini) used for baseline struct definition and switch logic.
Author: Iseoluwa Oluwapelumi Adedipe
Creation Date: September 17, 2026
Revision Date: September 17, 2026
*/

#include <stdio.h>    // Include standard I/O library for printf and fgets[cite: 8]
#include <string.h>   // Include string library for string manipulation functions[cite: 8]
#include <stdlib.h>   // Include standard library for integer conversion[cite: 8]

#define MAX_EMAILS 1000 // Define a constant for the maximum capacity of the priority queue[cite: 8]

// Source: Gemini baseline, heavily modified by Iseoluwa Adedipe for MaxHeap compliance[cite: 8]
typedef struct {        // Define a structure to hold all data for a single email[cite: 8]
    char sender[50];    // Character array to store the sender's category[cite: 8]
    char subject[150];  // Character array to store the subject line[cite: 8]
    char date[15];      // Character array to store the raw date string[cite: 8]
    int priority;       // Integer representing the categorical importance level[cite: 8]
    int year;           // Parsed integer for the email's year[cite: 8]
    int month;          // Parsed integer for the email's month[cite: 8]
    int day;            // Parsed integer for the email's day[cite: 8]
} Email;                // Name the struct 'Email'[cite: 8]

Email heap[MAX_EMAILS]; // Declare a global array of Emails to act as the list-based MaxHeap[cite: 8]
int heap_size = 0;      // Initialize the current number of emails in the heap to zero[cite: 8]

// Source: Authored by Iseoluwa Adedipe[cite: 8]
int get_priority(char *category) {                                 // Function to assign an integer priority based on the sender string[cite: 8]
    if (strcmp(category, "Boss") == 0) return 5;                   // Boss receives the highest priority (5)
    if (strcmp(category, "Subordinate") == 0) return 4;            // Subordinates receive the second highest priority (4)
    if (strcmp(category, "Peer") == 0) return 3;                   // Peers receive medium priority (3)[cite: 9]
    if (strcmp(category, "Important Person") == 0 || strcmp(category, "ImportantPerson") == 0) return 2; // Important Persons receive low priority (2)[cite: 9]
    return 1;                                                      // Other Persons receive the lowest priority (1)[cite: 9]
} // End of get_priority function[cite: 8]

// Source: Authored by Iseoluwa Adedipe[cite: 8]
int compare_emails(Email a, Email b) {                             // Function to determine which email has higher priority[cite: 8]
    if (a.priority != b.priority) return a.priority - b.priority;  // First, compare the integer priority tiers[cite: 8]
    if (a.year != b.year) return a.year - b.year;                  // If tied, newer year wins (higher value is better)[cite: 9]
    if (a.month != b.month) return a.month - b.month;              // If years tied, newer month wins[cite: 9]
    return a.day - b.day;                                          // If months tied, newer day wins[cite: 9]
} // End of compare_emails function[cite: 8]

// Source: Authored by Iseoluwa Adedipe[cite: 8]
void swap(int i, int j) {     // Function to swap two emails in the heap array[cite: 8]
    Email temp = heap[i];     // Store email at index i in a temporary variable[cite: 8]
    heap[i] = heap[j];        // Overwrite index i with the email at index j[cite: 8]
    heap[j] = temp;           // Place the temporary email into index j[cite: 8]
} // End of swap function[cite: 8]

// Source: Authored by Iseoluwa Adedipe[cite: 8]
void heapify_up(int index) {                                           // Function to restore MaxHeap property after insertion[cite: 8]
    if (index == 0) return;                                            // Base case: if at the root, stop[cite: 8]
    int parent = (index - 1) / 2;                                      // Calculate the parent index using array math[cite: 8]
    if (compare_emails(heap[index], heap[parent]) > 0) {               // If the current node is greater than its parent[cite: 8]
        swap(index, parent);                                           // Swap them to bubble the larger value up[cite: 8]
        heapify_up(parent);                                            // Recursively check the new position[cite: 8]
    }                                                                  // End of if statement[cite: 8]
} // End of heapify_up function[cite: 8]

// Source: Authored by Iseoluwa Adedipe[cite: 8]
void insert_email(char *sender, char *subj, char *date) {              // Function to parse strings and add email to heap[cite: 8]
    if (heap_size >= MAX_EMAILS) return;                               // Prevent buffer overflow if queue is full[cite: 8]
    Email e;                                                           // Declare a new Email struct[cite: 8]
    strcpy(e.sender, sender);                                          // Copy the sender string into the struct[cite: 8]
    strcpy(e.subject, subj);                                           // Copy the subject string into the struct[cite: 8]
    strcpy(e.date, date);                                              // Copy the date string into the struct[cite: 8]
    e.priority = get_priority(sender);                                 // Calculate and store the priority integer[cite: 8]
    sscanf(date, "%d-%d-%d", &e.month, &e.day, &e.year);               // Parse the date string into distinct integers for comparison[cite: 8]
    heap[heap_size] = e;                                               // Place the new email at the end of the heap array[cite: 8]
    heapify_up(heap_size);                                             // Bubble it up to its correct prioritized position[cite: 8]
    heap_size++;                                                       // Increment the total heap size tracker[cite: 8]
} // End of insert_email function[cite: 8]

// Source: Authored by Iseoluwa Adedipe[cite: 8]
void heapify_down(int index) {                                         // Function to restore MaxHeap property after extraction[cite: 8]
    int left = 2 * index + 1;                                          // Calculate left child index[cite: 8]
    int right = 2 * index + 2;                                         // Calculate right child index[cite: 8]
    int largest = index;                                               // Assume current node is the largest[cite: 8]
    if (left < heap_size && compare_emails(heap[left], heap[largest]) > 0)  // Check if left child exists and is greater than current largest[cite: 8]
        largest = left;                                                // Update largest to left child index[cite: 8]
    if (right < heap_size && compare_emails(heap[right], heap[largest]) > 0) // Check if right child exists and is greater than current largest[cite: 8]
        largest = right;                                               // Update largest to right child index[cite: 8]
    if (largest != index) {                                            // If the largest is not the current node[cite: 8]
        swap(index, largest);                                          // Swap the current node with the largest child[cite: 8]
        heapify_down(largest);                                         // Recursively push the node down the tree[cite: 8]
    }                                                                  // End of if statement[cite: 8]
} // End of heapify_down function[cite: 8]

// Source: Authored by Iseoluwa Adedipe[cite: 8]
void extract_max() {             // Function to remove the highest priority email (READ command)[cite: 9]
    if (heap_size == 0) return;  // Do nothing if the queue is already empty[cite: 9]
    heap[0] = heap[heap_size - 1]; // Move the last element in the array to the root position[cite: 8]
    heap_size--;                 // Decrease the overall heap size tracker[cite: 8]
    heapify_down(0);             // Re-sort the heap from the root downward[cite: 8]
} // End of extract_max function[cite: 8]

// Source: Authored by Iseoluwa Adedipe[cite: 8]
void peek_max() {                                                      // Function to display the highest priority email (NEXT command)[cite: 9]
    if (heap_size == 0) {                                              // Check if the heap is empty[cite: 8]
        printf("No emails in queue.\n");                               // Print fallback message[cite: 8]
        return;                                                        // Exit the function early[cite: 8]
    }                                                                  // End of if statement[cite: 8]
    printf("Next email:\n");                                           // Print the required header[cite: 9]
    printf("Sender: %s\n", heap[0].sender);                            // Print the sender category of the root email[cite: 9]
    printf("Subject: %s\n", heap[0].subject);                          // Print the subject line of the root email[cite: 9]
    printf("Date: %s\n", heap[0].date);                                // Print the raw date string of the root email[cite: 9]
} // End of peek_max function[cite: 8]

// Source: Gemini baseline, modified by Iseoluwa Adedipe for string parsing[cite: 8]
int main() {                                                           // Main function entry point[cite: 8]
    char buffer[256];                                                  // Character array buffer to hold incoming lines of text[cite: 8]
    while (fgets(buffer, sizeof(buffer), stdin) != NULL) {             // Loop to read standard input line by line until EOF[cite: 8]
        buffer[strcspn(buffer, "\r\n")] = 0;                           // Strip newline and carriage return characters from the buffer[cite: 8]
        if (strncmp(buffer, "EMAIL ", 6) == 0) {                       // Check if the command starts with 'EMAIL '[cite: 9]
            char *category = strtok(buffer + 6, ",");                  // Extract the category string before the first comma[cite: 8]
            char *subject = strtok(NULL, ",");                         // Extract the subject string before the second comma[cite: 8]
            char *date = strtok(NULL, "");                             // Extract the remainder of the string as the date[cite: 8]
            if (category && subject && date) {                         // Verify all three fields were successfully parsed[cite: 8]
                while(*subject == ' ') subject++;                      // Trim leading spaces from the subject[cite: 8]
                while(*date == ' ') date++;                            // Trim leading spaces from the date[cite: 8]
                insert_email(category, subject, date);                 // Insert the parsed data into the MaxHeap priority queue[cite: 8]
            }                                                          // End of inner if statement[cite: 8]
        } else if (strcmp(buffer, "NEXT") == 0) {                      // Check if the command is exactly 'NEXT'[cite: 9]
            peek_max();                                                // Display the highest priority email without removing it[cite: 8]
        } else if (strcmp(buffer, "READ") == 0) {                      // Check if the command is exactly 'READ'[cite: 9]
            extract_max();                                             // Remove the highest priority email from the queue[cite: 8]
        } else if (strcmp(buffer, "COUNT") == 0) {                     // Check if the command is exactly 'COUNT'[cite: 9]
            printf("There are %d emails to read.\n", heap_size);       // Print the current total number of emails in the heap[cite: 9]
        }                                                              // End of else-if chain[cite: 8]
    }                                                                  // End of while loop[cite: 8]
    return 0;                                                          // Return 0 to indicate successful program execution[cite: 8]
} // End of main function[cite: 8]